```{r}
library(tidyverse)
library(tidymodels)
load('../data/biomarker-clean.RData')
biomarker <- biomarker_clean %>%
  mutate(class = as.numeric(group == 'ASD')) %>% 
  select(-ados, -group)
```


```{r}
# partition
set.seed(101622)
partitions <- biomarker %>%
  initial_split(prop = 0.8, strata = class)

biomarker_train <- training(partitions)
biomarker_test <- testing(partitions)
```

```{r}
# ALl proteins as identified by the three methods in the paper
# First 5 are identified by all methdos (core panel)
max_predictors <- c("DERM", "suPAR", "MAPK14", "IgD", "EPHB2", 
                    "ALCAM", "`eIF-4H`", "SOST", "C6", "Calcineurin",
                    "FCN1", "C1QR1", "PTN", "RELT", "`Prolactin Receptor`", "ROR1",
                    "GI24", "ARSB")

max_formula <- as.formula(paste("class ~", paste(max_predictors, collapse = "+")))

full_fit <- glm(max_formula, data = biomarker_train, family = binomial)
null_fit <- glm(class ~ 1, data = biomarker_train, family = binomial)

forward_model <- stats::step(null_fit, direction = "forward", 
                             scope = list(lower = null_fit, upper = full_fit))

```

```{r}
class_metrics <- metric_set(sensitivity, specificity, accuracy)

biomarker_test %>% 
  select(forward_model$model %>% colnames()) %>% 
  modelr::add_predictions(model = forward_model, type = "response") %>% 
  mutate(est = as.factor(pred>0.5), tr = as.factor(ifelse(class == 1, T, F))) %>%
  class_metrics(truth = tr, estimate = est, event_level = "second")

```


